// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.0 <0.9.0;

/**
 * @title PaymentVerifier
 * @dev Manages ZK proof verification for payment transactions on Polygon Amoy
 */
contract PaymentVerifier {
    // Reference to the Groth16 verifier contract
    Verifier public verifier;

    // Struct to track verified payments
    struct VerifiedPayment {
        address user;
        uint256 amount;
        bytes32 pinHash;
        uint256 timestamp;
        bool isVerified;
    }

    // Mapping: paymentId => VerifiedPayment
    mapping(uint256 => VerifiedPayment) public payments;
    
    // Mapping: user => list of payment IDs
    mapping(address => uint256[]) public userPayments;

    uint256 public paymentCounter = 0;

    event PaymentVerified(uint256 indexed paymentId, address indexed user, uint256 amount);
    event PaymentRegistered(uint256 indexed paymentId, address indexed user, uint256 amount);

    constructor(address _verifierAddress) {
        verifier = Verifier(_verifierAddress);
    }

    /**
     * @dev Register a new payment intent with PIN hash
     * @param amount The payment amount in wei
     * @param pinHash The Poseidon hash of PIN + Salt
     */
    function registerPayment(uint256 amount, bytes32 pinHash) public returns (uint256) {
        uint256 paymentId = paymentCounter;
        paymentCounter++;

        payments[paymentId] = VerifiedPayment({
            user: msg.sender,
            amount: amount,
            pinHash: pinHash,
            timestamp: block.timestamp,
            isVerified: false
        });

        userPayments[msg.sender].push(paymentId);
        emit PaymentRegistered(paymentId, msg.sender, amount);

        return paymentId;
    }

    /**
     * @dev Verify a ZK proof and mark payment as verified
     * @param paymentId The payment ID to verify
     * @param a First part of the proof
     * @param b Second part of the proof
     * @param c Third part of the proof
     * @param input Public signals from the circuit
     */
    function verifyPayment(
        uint256 paymentId,
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input
    ) public {
        require(paymentId < paymentCounter, "Payment does not exist");
        require(!payments[paymentId].isVerified, "Payment already verified");
        require(payments[paymentId].user == msg.sender, "Not authorized");

        // Call the Groth16 verifier
        require(verifier.verifyProof(a, b, c, input), "Invalid ZK proof");

        // Mark payment as verified
        payments[paymentId].isVerified = true;
        emit PaymentVerified(paymentId, msg.sender, payments[paymentId].amount);
    }

    /**
     * @dev Get payment details
     */
    function getPayment(uint256 paymentId)
        public
        view
        returns (VerifiedPayment memory)
    {
        require(paymentId < paymentCounter, "Payment does not exist");
        return payments[paymentId];
    }

    /**
     * @dev Get all payments for a user
     */
    function getUserPayments(address user) public view returns (uint256[] memory) {
        return userPayments[user];
    }
}

// Placeholder for Verifier contract (will be auto-generated by snarkjs)
interface Verifier {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[1] memory input
    ) external view returns (bool);
}
