// Hardhat deployment script for Polygon Amoy Testnet
// Run: npx hardhat run scripts/deploy.js --network amoy

async function main() {
  console.log("Deploying ZK Payment Verifier contracts...");

  // 1. Deploy Verifier contract (auto-generated by snarkjs)
  console.log("\n1. Deploying Verifier contract...");
  const Verifier = await ethers.getContractFactory("Verifier");
  const verifier = await Verifier.deploy();
  await verifier.deployed();
  console.log("✓ Verifier deployed to:", verifier.address);

  // 2. Deploy PaymentVerifier contract
  console.log("\n2. Deploying PaymentVerifier contract...");
  const PaymentVerifier = await ethers.getContractFactory("PaymentVerifier");
  const paymentVerifier = await PaymentVerifier.deploy(verifier.address);
  await paymentVerifier.deployed();
  console.log("✓ PaymentVerifier deployed to:", paymentVerifier.address);

  // 3. Save deployment addresses to file
  const fs = require("fs");
  const deploymentInfo = {
    network: "Polygon Amoy Testnet",
    verifierAddress: verifier.address,
    paymentVerifierAddress: paymentVerifier.address,
    deploymentTime: new Date().toISOString(),
  };

  fs.writeFileSync(
    "blockchain/deployments.json",
    JSON.stringify(deploymentInfo, null, 2)
  );

  console.log("\n✓ Deployment complete!");
  console.log("Saved to blockchain/deployments.json");
  console.log("\nDeployment Info:");
  console.log(deploymentInfo);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
